name: Update euribor data

concurrency:
  group: "update"
  cancel-in-progress: true

on:
  workflow_dispatch:

  schedule:
    # Runs "At 20:00." (see https://crontab.guru)
    - cron: '0 20 * * *'

jobs:
  update:
    runs-on: ubuntu-20.04
    steps:
      - name: 'What time is it?'
        id: time
        run: |
          echo "now=$(date +'%Y%m%d_%H%M%S')" >> $GITHUB_OUTPUT
          echo "prettynow=$(date +'%Y/%m/%d %H:%M:%S')" >> $GITHUB_OUTPUT
      - name: Prepare runtime
        run: sudo snap install htmlq
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Scrape euribor info
        run: bash ./scrape.sh
      - name: Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          branch: update-data-${{ steps.time.outputs.now }}
          title:          "[${{ steps.time.outputs.prettynow }}] update EURIBOR/EURIS data"
          commit-message: "[${{ steps.time.outputs.prettynow }}] update EURIBOR/EURIS data"
          body:           "Scraping from https://www.euribor.it/ - checked at ${{ steps.time.outputs.prettynow }}"
          delete-branch: true
          labels: patch